// All badges in the game
// key must be unique — used to check if user already has it

export const BADGES = [
  {
    key:         "gene_seed_activated",
    name:        "Gene-Seed Activated",
    description: "Completed onboarding. Your journey begins.",
    universe:    "Warhammer 40K",
    icon:        "🧬",
    xpReward:    100,
    secret:      false,
  },
  {
    key:         "baptism_of_iron",
    name:        "Baptism of Iron",
    description: "Completed your very first workout.",
    universe:    "Warhammer 40K",
    icon:        "🩸",
    xpReward:    150,
    secret:      false,
  },
  {
    key:         "burning_crusade",
    name:        "The Burning Crusade",
    description: "Reached a 3 day workout streak.",
    universe:    "Warhammer 40K",
    icon:        "🔥",
    xpReward:    200,
    secret:      false,
  },
  {
    key:         "oath_of_moment",
    name:        "Oath of Moment",
    description: "Reached a 7 day workout streak.",
    universe:    "Warhammer 40K",
    icon:        "⚔️",
    xpReward:    500,
    secret:      false,
  },
  {
    key:         "eternal_warrior",
    name:        "Eternal Warrior",
    description: "Reached a 30 day workout streak.",
    universe:    "Marvel",
    icon:        "🧠",
    xpReward:    2000,
    secret:      false,
  },
  {
    key:         "hundred_worlds",
    name:        "Hundred Worlds",
    description: "Completed 100 total workout sessions.",
    universe:    "Warhammer 40K",
    icon:        "🏛️",
    xpReward:    3000,
    secret:      false,
  },
  {
    key:         "whale_shark_protocol",
    name:        "Whale Shark Protocol",
    description: "Lifted over 1,000kg in a single session.",
    universe:    "FitAI Original",
    icon:        "🦈",
    xpReward:    500,
    secret:      false,
  },
  {
    key:         "mjolnir_lift",
    name:        "Mjolnir Lift",
    description: "Set a new personal best on any exercise.",
    universe:    "Norse/Marvel",
    icon:        "👑",
    xpReward:    200,
    secret:      false,
  },
  {
    key:         "dawn_crusader",
    name:        "Dawn Crusader",
    description: "Logged a workout before 7am.",
    universe:    "Warhammer 40K",
    icon:        "🌅",
    xpReward:    150,
    secret:      true,
  },
  {
    key:         "night_lords",
    name:        "Night Lords",
    description: "Logged a workout after 10pm.",
    universe:    "Warhammer 40K",
    icon:        "🌙",
    xpReward:    150,
    secret:      true,
  },
  {
    key:         "servo_skull_vision",
    name:        "Servo-Skull Vision",
    description: "Uploaded your first form check video.",
    universe:    "Warhammer 40K",
    icon:        "🎥",
    xpReward:    200,
    secret:      false,
  },
  {
    key:         "leviathan_class",
    name:        "Leviathan Class",
    description: "Lifted 10,000kg total across all sessions.",
    universe:    "Warhammer 40K",
    icon:        "🌊",
    xpReward:    1000,
    secret:      false,
  },
  {
    key:         "unbroken_chain",
    name:        "Unbroken Chain",
    description: "Completed 4 workouts in a single week.",
    universe:    "Warhammer 40K",
    icon:        "💎",
    xpReward:    300,
    secret:      false,
  },
  {
    key:         "eye_of_empyrean",
    name:        "Eye of the Empyrean",
    description: "Received AI feedback on a form check.",
    universe:    "Warhammer 40K",
    icon:        "👁️",
    xpReward:    200,
    secret:      false,
  },
];

export function getBadgeByKey(key) {
  return BADGES.find((b) => b.key === key);
}
